"""Add workflow query indexes

Revision ID: b671dd9b4546
Revises: f1bcc720fb19
Create Date: 2026-10-06 00:54:21.041236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b671dd9b4546'
down_revision = 'f1bcc720fb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index('ix_claims_item_status', ['item_id', 'status'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_category_status', ['category', 'status'], unique=False)
        batch_op.create_index('ix_items_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_items_type_status_created', ['type', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read_created', ['user_id', 'is_read', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read_created')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_type_status_created')
        batch_op.drop_index('ix_items_status_created')
        batch_op.drop_index('ix_items_category_status')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_item_status')

    # ### end Alembic commands ###
